"""
User Agreement & Terms of Service router.
"""
from datetime import datetime, timezone
from bson import ObjectId
from fastapi import APIRouter, Depends, HTTPException, status

from app.database import users_collection
from app.schemas.agreement import (
    AgreementTermsOut,
    AgreementAcceptPayload,
    AgreementStatusOut,
)
from app.utils.deps import get_current_user, DEFAULT_GUEST_USER

router = APIRouter(prefix="/api/agreement", tags=["Agreement"])

TERMS_DATA = {
    "version": "1.0.0",
    "title": "AI Voice Assistant User Agreement & Terms of Service",
    "last_updated": "2026-08-11",
    "content": "Welcome to AI Voice Assistant. By using our platform, you agree to these Terms of Service, Privacy Policy, and AI Usage Guidelines.",
    "sections": [
        {
            "heading": "1. Acceptance of Terms",
            "body": "By registering an account or interacting with the AI Voice Assistant service, you confirm that you have read, understood, and agreed to be bound by this User Agreement."
        },
        {
            "heading": "2. Voice & Audio Data Privacy",
            "body": "Audio input recorded during voice sessions is processed to transcribe and respond to your queries. Your voice recordings are handled securely and are never shared with unauthorized third parties."
        },
        {
            "heading": "3. AI Usage & Content Disclaimer",
            "body": "Responses generated by the AI Assistant are provided for informational and productivity purposes. While we strive for accuracy, AI responses should be independently verified for critical tasks."
        },
        {
            "heading": "4. User Conduct & Account Security",
            "body": "You are responsible for maintaining the confidentiality of your account credentials and for all activities conducted under your account."
        },
        {
            "heading": "5. Terms Updates & Termination",
            "body": "We reserve the right to update these terms at any time. Continued use of the platform after updates constitutes acceptance of the revised agreement."
        }
    ]
}


@router.get("/terms", response_model=AgreementTermsOut)
async def get_terms():
    """
    Returns the latest Terms of Service and User Agreement document.
    """
    return AgreementTermsOut(**TERMS_DATA)


@router.get("/status", response_model=AgreementStatusOut)
async def get_agreement_status(current_user: dict = Depends(get_current_user)):
    """
    Returns the current user's agreement acceptance status.
    """
    user_id = str(current_user.get("_id", ""))
    return AgreementStatusOut(
        user_id=user_id,
        agreed_to_terms=current_user.get("agreed_to_terms", True),
        agreed_at=current_user.get("agreed_at"),
    )


@router.post("/accept", response_model=AgreementStatusOut)
async def accept_terms(
    payload: AgreementAcceptPayload,
    current_user: dict = Depends(get_current_user)
):
    """
    Records or updates the user's consent to the Terms of Service.
    """
    user_id = str(current_user.get("_id", ""))
    if user_id == str(DEFAULT_GUEST_USER["_id"]):
        return AgreementStatusOut(
            user_id=user_id,
            agreed_to_terms=payload.agreed,
            agreed_at=datetime.now(timezone.utc).isoformat(),
        )

    now_iso = datetime.now(timezone.utc).isoformat()
    await users_collection.update_one(
        {"_id": ObjectId(user_id)},
        {"$set": {"agreed_to_terms": payload.agreed, "agreed_at": now_iso}}
    )

    return AgreementStatusOut(
        user_id=user_id,
        agreed_to_terms=payload.agreed,
        agreed_at=now_iso,
    )
