import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowLeft, ShieldCheck, FileText, CheckCircle2, Lock, Cpu, Globe } from 'lucide-react'
import { useTheme } from '../context/ThemeContext'
import { agreementAPI } from '../services/api'
import { BackgroundGlow } from './Login'

export default function Terms() {
  const { theme } = useTheme()
  const isLight = theme === 'light'
  const [terms, setTerms] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    agreementAPI
      .getTerms()
      .then((res) => setTerms(res.data))
      .catch(() => {
        setTerms({
          version: '1.0.0',
          title: 'AI Voice Assistant User Agreement & Terms of Service',
          last_updated: '2026-08-11',
          content: 'Welcome to AI Voice Assistant. By using our platform, you agree to these Terms of Service, Privacy Policy, and AI Usage Guidelines.',
          sections: [
            {
              heading: '1. Acceptance of Terms',
              body: 'By registering an account or interacting with the AI Voice Assistant service, you confirm that you have read, understood, and agreed to be bound by this User Agreement.',
            },
            {
              heading: '2. Voice & Audio Data Privacy',
              body: 'Audio input recorded during voice sessions is processed to transcribe and respond to your queries. Your voice recordings are handled securely and are never shared with unauthorized third parties.',
            },
            {
              heading: '3. AI Usage & Content Disclaimer',
              body: 'Responses generated by the AI Assistant are provided for informational and productivity purposes. While we strive for accuracy, AI responses should be independently verified for critical tasks.',
            },
            {
              heading: '4. User Conduct & Account Security',
              body: 'You are responsible for maintaining the confidentiality of your account credentials and for all activities conducted under your account.',
            },
            {
              heading: '5. Terms Updates & Termination',
              body: 'We reserve the right to update these terms at any time. Continued use of the platform after updates constitutes acceptance of the revised agreement.',
            },
          ],
        })
      })
      .finally(() => setLoading(false))
  }, [])

  return (
    <div className={`min-h-screen w-full relative overflow-hidden transition-colors font-sans py-12 px-4 select-none ${
      isLight ? 'bg-slate-50 text-slate-900' : 'bg-[#05070e] text-white'
    }`}>
      <BackgroundGlow isLight={isLight} />

      <div className="max-w-3xl mx-auto relative z-10">
        {/* Back navigation */}
        <Link
          to="/dashboard"
          className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-xl text-xs font-semibold mb-6 transition cursor-pointer ${
            isLight ? 'bg-white border border-slate-200 text-slate-700 hover:bg-slate-100' : 'bg-slate-900 border border-white/10 text-slate-300 hover:bg-slate-800'
          }`}
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Dashboard</span>
        </Link>

        {/* Title Header */}
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <div className="flex items-center gap-3 mb-2">
            <div className="p-3 rounded-2xl bg-indigo-600/10 text-indigo-500 border border-indigo-500/20">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight">
                User Agreement & Terms
              </h1>
              <p className={`text-xs ${isLight ? 'text-slate-500' : 'text-slate-400'}`}>
                Official Terms of Service, Privacy Policy & Voice Data Handling Agreement
              </p>
            </div>
          </div>
        </motion.div>

        {/* Card Container */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className={`rounded-3xl border p-6 md:p-8 backdrop-blur-xl shadow-2xl space-y-6 ${
            isLight ? 'bg-white/90 border-slate-200 shadow-indigo-500/5' : 'bg-slate-950/75 border-white/10'
          }`}
        >
          {loading ? (
            <div className="flex justify-center py-16">
              <div className="w-8 h-8 border-3 border-indigo-500 border-t-transparent rounded-full animate-spin" />
            </div>
          ) : (
            <>
              {/* Highlight Box */}
              <div className={`p-4 rounded-2xl border flex items-start gap-3 text-xs leading-relaxed ${
                isLight ? 'bg-indigo-50/70 border-indigo-200 text-indigo-950' : 'bg-indigo-500/10 border-indigo-500/30 text-indigo-200'
              }`}>
                <ShieldCheck className="w-5 h-5 text-indigo-500 shrink-0 mt-0.5" />
                <div>
                  <span className="font-bold block mb-0.5">Agreement Summary</span>
                  {terms?.content}
                </div>
              </div>

              {/* Sections list */}
              <div className="space-y-6">
                {terms?.sections?.map((section, idx) => (
                  <div key={idx} className="space-y-2">
                    <h2 className="text-sm font-bold text-indigo-400 flex items-center gap-2">
                      <span className="w-1.5 h-1.5 rounded-full bg-indigo-500" />
                      {section.heading}
                    </h2>
                    <p className={`text-xs leading-relaxed pl-3.5 border-l-2 ${
                      isLight ? 'border-slate-200 text-slate-700' : 'border-white/10 text-slate-300'
                    }`}>
                      {section.body}
                    </p>
                  </div>
                ))}
              </div>

              {/* Trust Badges */}
              <div className={`pt-6 border-t grid grid-cols-1 md:grid-cols-3 gap-3 ${
                isLight ? 'border-slate-200' : 'border-white/10'
              }`}>
                <div className="flex items-center gap-2 text-xs font-medium text-emerald-400">
                  <Lock className="w-4 h-4 shrink-0" />
                  <span>256-bit Encryption</span>
                </div>
                <div className="flex items-center gap-2 text-xs font-medium text-cyan-400">
                  <Cpu className="w-4 h-4 shrink-0" />
                  <span>Private AI Processing</span>
                </div>
                <div className="flex items-center gap-2 text-xs font-medium text-indigo-400">
                  <Globe className="w-4 h-4 shrink-0" />
                  <span>GDPR / CCPA Compliant</span>
                </div>
              </div>
            </>
          )}
        </motion.div>
      </div>
    </div>
  )
}
